//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeID { get; set; }
        public string EmployeeFullName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string PassportNumber { get; set; }
        public string BankAccountNumber { get; set; }
        public string FamilyStatus { get; set; }
        public string HealthIssues { get; set; }
        public string JobTitle { get; set; }
        public string Department { get; set; }
        public string Specialization { get; set; }
        public bool MasterOfProduction { get; set; }
        public string NFCcardID { get; set; }
        public Nullable<System.DateTime> CheckInTime { get; set; }
        public Nullable<System.DateTime> CheckOutTime { get; set; }
    }
}
