//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Production
    {
        public int ProductionId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> NumberOfEmployees { get; set; }
        public string Materials { get; set; }
    
        public virtual ShopProduct ShopProduct { get; set; }
    }
}
